import './globals.css';

import { Chakra_Petch, Inter } from 'next/font/google';

import type { Metadata } from 'next';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const chakra = Chakra_Petch({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	variable: '--font-chakra',
});

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
});

type RootLayoutProps = Readonly<{
	children: React.ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={cn(inter.variable, chakra.variable, ' font-sans antialiased')}>
				<NuqsAdapter>
					<ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
						{children}
						<Toaster />
					</ThemeProvider>
				</NuqsAdapter>
			</body>
		</html>
	);
}
